### ISSUE TITLE
Hope can add an option to delete old checkboxes

### ISSUE THREAD

**Issue by Callioper** [shichongrui/obsidian-rollover-daily-todos#10]
Just like cut instead of copy.

**Comment by jpmoo** [comment]
I second this. Either delete, or render them “inert” somehow (mark them complete or turn them into simple list items). This will allow the plug-in to play nicer with others that summarize or interact with todos (like the Tasks plugin).

**Comment by KjellConnelly** [comment]
Added this feature in release `1.0.5`. It's now an option in the plugin Settings. Since the code is somewhat new, I also added a `Undo Rollover` command. That way, if you toggle on the delete option, and for whatever reason, you don't like the result, you will have 2 mins to run the Undo command. Let me know if after trying this, there are any issues with it.
