### ISSUE TITLE
Suggestion on roll-over todos to existed daily notes

### ISSUE THREAD

**Issue by ONLYA** [shichongrui/obsidian-rollover-daily-todos#16]
This is a great plugin and has made the beginning of a new day much easier. 
I am currently using it with the Calendar plugin. 
It could be better if the unchecked TODO's can be carried to an existing daily note because I will pre-create a daily note to set scheduled events.

**Comment by KjellConnelly** [comment]
Hi @ONLYA, I just added version `1.0.5` which has a new command (from command palette) which can run the rollover command on demand. Todos will only be rolled over to the current daily note from the previous note that exists before this day. For example:

#### Example

##### Setup
- You have daily notes every day without exception in the format `YYYY-MM-DD`
- On a regular basis, you create a daily note at night, for the next day to prep.

##### Process
- It's Wednesday night, and you create a new daily note for tomorrow (Thursday) using the `Calendar plugin`.
- You run the `Rollover Todos Now` command from the command Palette, which results in:
  - Todos from yesterday (tuesday) rollover to today's daily note (Wednesday)
  - Since there are no todos from Tuesday to roll over, nothing happens.
- You go to sleep, and the next morning you wake up and open your Daily Note for Thursday. It still is populated with the same todos you the night before (None have been rolled over from Wednesday yet).
- You run the `Rollover Todos Now` command again. Now all todos from Wednesday are rolled over to Thursday.

Unfortunately, there is no command currently to roll Today's todos over to tomorrow. But you can wait until tomorrow to roll them over now. I think it could get a bit messy for users, as well as writing the code for it, to be able to roll todos over preemptively (from Today to Tomorrow). So for now, unless you have any ideas on user workflow, I think the functionality seems to be at a good place. Feel free to reopen this issue if the current solution doesn't work for you. Otherwise, I'm clearing out issues at the moment and don't plan on coming back to this one unless there's a straightforward solution that improves upon my current one.
