### ISSUE TITLE
Support exclude some checkboxes

### ISSUE THREAD

**Issue by Liquidmantis** [shichongrui/obsidian-rollover-daily-todos#6]
It would be great if there was a way to set RDT to either only look at items under the select heading, or to ignore a/some headings.  In my use case, I have a Todos heading where I add items, but I also have a Daily Tasks heading that is defined in my template with a set of things that I'd ideally get done every day.  

I might not actually get them all done though, and right now RDT will add them to my Todos list on a new day, which is redundant with the new day's Daily Tasks that the template adds.  Ideally I could configure RDT to ignore the Daily Tasks heading, or to only look at items in the Todos heading, where it currently adds the rollover items.

**Comment by KjellConnelly** [comment]
Hi @Liquidmantis, I am thinking about implementing something like this. It looks like a lot of code though, so I probably won't get around to it soon. Feel free to reopen this if you or someone else wants to discuss implementation or making a pull request themself. But here's pretty much what I want, where input is the previous daily note, and output is today's daily note:

## How it currently works:

#### Input

- All unfinished Todos are grabbed, no matter what heading they are in.

#### Output

##### Situation 1: No Template Heading is set (from the Plugin's Settings Menu)

- All todos are rolled over to the bottom of the file

##### Situation 2: Template Heading is set, and Heading is found

- All todos are rolled over, just under the Heading selected

##### Situation 3: Template Heading is set, and Heading is not found

- All todos are rolled over to the bottom of the file

## How I'd like it to work:

#### Input

##### Situation 1: No Template Heading is set

- All unfinished Todos are grabbed, no matter what heading they are in.

##### Situation 2: Template Heading is set, and Heading is found

- All unfinished Todos are grabbed that are under this heading ONLY. Subheadings are taken into account (like if your Template Heading is a `##`, and you have `###` and `####` under it, it'll grab those too, but not unfinished todos in the next `##` or `#`.

##### Situation 3: Template Heading is set, and Heading is not found

- All unfinished Todos are grabbed, no matter what heading they are in.

#### Output

##### Situation 1: No Template Heading is set

- All todos are rolled over to the bottom of the file

##### Situation 2: Template Heading is set, and Heading is found

- All subheadings are populated with the appropriate unfinished todos
- If the main heading is found, but not all subheadings are, subheadings are created based on the input file

##### Situation 3: Template Heading is set, and Heading is not found

- If the template heading was found in the input file, the Heading and Subheadings are created and populated based off of the input file
- Otherwise, all todos are rolled over to the bottom of the file
